// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function EnableService(arg1:string):Promise<boolean|string>;

export function GetKernelHealth():Promise<Record<string, any>>;

export function GetKernelStatus():Promise<string>;

export function GetServices():Promise<Array<main.ServiceStatus>>;

export function GetWorkspaceRoot():Promise<string>;

export function OpenCogChat():Promise<boolean|string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartService(arg1:string):Promise<boolean|string>;

export function StartService(arg1:string):Promise<boolean|string>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<boolean|string>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
