// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function EnableService(arg1) {
  return window['go']['main']['App']['EnableService'](arg1);
}

export function GetKernelHealth() {
  return window['go']['main']['App']['GetKernelHealth']();
}

export function GetKernelStatus() {
  return window['go']['main']['App']['GetKernelStatus']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetWorkspaceRoot() {
  return window['go']['main']['App']['GetWorkspaceRoot']();
}

export function OpenCogChat() {
  return window['go']['main']['App']['OpenCogChat']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
